config/routes.rb
Rails.application.routes.draw do

  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

  get 'tweets' => 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :name, :content ,presence: true, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end
  
  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
      redirect_to tweets_path, notice: "ツイートしました！"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @tweet.update(tweets_params)
      redirect_to tweets_path, notice: "編集しました！"
    else
      render :edit
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
    def tweets_params
      params.require(:tweet).permit(:name, :content)
    end
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeve</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "ホーム", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "ツイート", new_tweet_path %></li>
                <li><%= link_to "ツイート一覧", tweets_path %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
  　  </div><!-- /.container-fluid -->
  　</nav>
　</header>
<%= yield %>
  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<section class="about">
  <h1>いまどうしてる？</h1>
  <p>
     Tweeveは、Achieveを参考に作成された、Twitter風アプリです。
  </p>
</section>

<section class="main-header">
  <img src="<%= asset_path "tweeve.png" %>">
</section>

<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :ユーザー名 %>
<%= f.text_field :name, class: 'form-control' %>
<br>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '確認', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、ツイートする。</h3>
    <%= form_for(@tweet) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :content %>
      <p>ユーザー名:<%= @tweet.name %></p>
      <p>本文:<%= @tweet.content %></p>
      <%= f.submit "ツイート",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <h2>ツイートを編集</h2>
  <%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ツイート一覧</h1>
      <%= link_to "ツイート", new_tweet_path, class: 'btn btn-default' %>
    <% @tweets.each do |tweet| %>
    <div class="row">
      <p><%= tweet.name %></p>
      <h4><strong><%= tweet.content %></strong></h4>
      <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートする</h2>
    <%= render 'form' %>
  </div>
</div>